services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: dimenter
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411 # Port used for the Zipkin UI and HTTP Api

  rabbitmq:
    image: rabbitmq:3.11.13-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672 # Для коннекта с микросервисами
      - 15672:15672 # Админ панель

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: