server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

  # Configuring API Gateway
  cloud:
    gateway:
      routes:
        - id: customer # добавляем микросервис customer
          uri: lb://CUSTOMER # берется из eureka server
          predicates:
            - Path=/api/v1/customers/** # позволяем использовать любые запросы по этому пути
        - id: fraud # добавляем микросервис customer
          uri: lb://FRAUD # берется из eureka server
          predicates:
            - Path=/api/v1/fraud-check/** # позволяем использовать любые запросы по этому пути

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Trace every action
management:
  tracing:
    sampling:
      probability: 1.0 #default 0.1